# Linear Algebra

In [47]:
import numpy as np
import math
import numpy.linalg as la
from numpy.linalg import norm, inv
from numpy import transpose
verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001

** Vectors ** <br>
Column or row vectors.

$\overrightarrow{v} = \begin{bmatrix}
  x_{1} \\
  x_{2} \\
  x_{3} \\
\end{bmatrix}$

**Real coordinate space** <br>
${\rm I\!R}^2$ Two dimensional real coordinate space: all possible real valued tuples. <br>
${\rm I\!R}^3$ Three dimensional real coordinate space. <br>
${\rm I\!R}^n$ n dimensional real coordinate space. <br>
Tuples are ordered. <br>

$\overrightarrow{v} \in {\rm I\!R}^3$

** modulus size of vector **
$||r||^2 =\sum_{i}r_{i}^2$ 

** dot product of vectors **
$r.s = \sum_{i}r_{i}  s_{i}$

** scalar projection of vector s onto r **
  $\frac{r.s}{||r||}$

** vector projection of vector s onto r **
  $r.\frac{r.s}{r.r}$
  
** cosine rule and dot product ** <br>
$c^2 = a^2 + b^2 - 2ab \cos{\theta}$ <br>
$s.r = |r| |s|\cos\theta $

** Gaussian / Normal distribution **

** Sum of Squared Residuals ** <br>
SSR(**p**) = $|f - g_{p}$|

__Determinant__<br>
Determinant is the scale of the space is what the determinant is. By dividing by the determinant, we're normalizing the space back to its original size.<br>
$ A = 
\begin{vmatrix}
a & b \\
c & d \\
\end{vmatrix}
$ then $Det(A) = ad - cd$

In [8]:
#compute determinant using numpy
np.linalg.det([[1,2],[1,2]])

0.0

Linear independance basis vector set $v = \{v_{1},v_{2}...v_{n}\}$ by checking that determinant isn't zero or $\neq 0$. Linear dependant then determinant is zero or = 0.

# Matrices
** matrix inverse **
<br>
$A^{-1} A = A A^{-1} = I$
<br>
$Ar=s <=> A^{-1}Ar=A^{-1}s <=> r=A^{-1}s$

A matrix is called singular if it has no inverse or its determinant is zero.

Reduce a matrix to **echelon form**.

Einstein Summation Convention: $C_{ik} = a_{ij}b_{jk}$

changing basis: $Mbearsworld_{targetbasis} * V_{bearsworld} = V_{targetbasis}$ <br>
$\>\>\> or \space [M_{bearsworld}]_{targetbasis} * [V]_{bearsworld} = [V]_{targetbasis}$<br><br>
inverse changing basis: $Mbearsworld_{targetbasis}^{-1} * V_{targetbasis} = V_{bearsworld}$ <br>
When the basis are orthonormal the vector projection can be used instead.

__Matrix Transformation__: <br>
$B^{-1} R B$ <br>
$r'=A_{ij}r_{j}$ (einstein notation)<br>
$R'_{ia}=A_{ij}R_{ja}$ (einstein notation) <br>
$r' = E T_{E} E^{-1} r$ E is orthonormal with $E^{T} = E^{-1}$

In [7]:
# numpy matrix multiplication
A = np.array([[1,0,1/3],[0,1,-1/4]])
R = np.array([[5,-1,-3,7],[4,-4,1,-2],[9,3,0,12]])
np.matmul(A,R)

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])

When is A orthogonal $A^{T} = A^{-1} <=> A^{T}A=A^{-1}A=I$ <br>
columns or rows of A are orthonormal. $a_{i} . a_{j} = 0 \space when \space i \neq j$ <br>
$ |A| = ± 1 $ <br> <br>
Most convenient basis vector set: orthonormal basis vector set.

# Eigen Values / Vectors
Finding characteric properties of a matrix transformation:
* eigen vectors their direction did not change only their scale
* eigen vectors laying on the same span after transformation
<br>
$Ax = \lambda x$ <br>
$(A-\lambda I)x = 0$ <=> $det(A-\lambda I)=0$ <br>
$A = \begin{vmatrix}
a & b \\
c & d
\end{vmatrix}$ then det($\begin{vmatrix}
a & b \\
c & d
\end{vmatrix}$ - $\begin{vmatrix}
\lambda & 0 \\
0 & \lambda
\end{vmatrix}$) = $\lambda^2 - (a+d) \lambda + ad - bc = 0$ <br>
The eigen values are the solution the equation above!

In [29]:
#numpy eigen values
la.eigvals(np.array([[1,0],[-1,4]]))

array([4., 1.])

# Eigen Basis
Diagonal matrices make things a lot easier when raising a matrix to certain power: 
$ T^n = 
\begin{vmatrix}
a^{n} & 0 & 0 \\
0 & b^{n} & 0 \\
0 & 0 & c^{n}
\end{vmatrix}
$ <br>

$ A =
\begin{vmatrix}
2 & 0 \\
0 & 2
\end{vmatrix}
$ 
$\space then \space
A^{3} = 
\begin{vmatrix}
8 & 0 \\
0 & 8
\end{vmatrix}
$

Change to eigen basis; if column of our transformed matrix simply represents the new location of the transformed unit vectors. 

$ C = 
\begin{vmatrix}
x_{1} & x_{2} & x_{3} \\
. & . & . \\
. & . & .
\end{vmatrix}
$ with $x_{1}, x_{2} \space and \space x_{3}$ being eigen vectors.

$ D = 
\begin{vmatrix}
\lambda_{1} & 0 & 0 \\
0 & \lambda_{2} & 0 \\
0 & 0 & \lambda_{3}
\end{vmatrix}
$ with $\lambda_{1}, \lambda_{1} \space and \space \lambda_{3}$ being eigen values.

With matrix transformation T find corresponding eigenbasis C en diagonal matrix with eigen values D, then the following holds:

$T = CDC^{-1}$ <br>
$D = C^{-1}TC$ <br>
$T^n = CD^{n}C^{-1}$

# Page Rank
Vector r stores all ranks of internet pages: what's your rank, do you link to page A and how many outgoing links do you have in total. L is the link matrix. j to n are web pages. Rank of A is the sum of all the ranks of web pages linking to it weighted by specific link probability taken from matrix L.<br><br>
$r_{A} = \sum_{j=1}^n L_{A.j}r_{j}$ <br>
This effectively searching for eigen values: <br>
$r^{i+1} = Lr^{i}$ repeat using power method until converges! (simple formula) $<=> \lambda r = Lr \space with \space \lambda = 1 \space <=> r = Lr$ <br>
$r^{i+1} = d(Lr^{i}) + \frac{1-d}{n}$ repeat using power method until converges! <br>

# Numpy Code

In [28]:
# Our function will go through the matrix replacing each row in order turning it into echelon form.
# If at any point it fails because it can't put a 1 in the leading diagonal,
# we will return the value True, otherwise, we will return False.
# There is no need to edit this function.
def isSingular(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# This next line defines our error flag. For when things go wrong if the matrix is singular.
# There is no need to edit this line.
class MatrixIsSingular(Exception): pass

# For Row Zero, all we require is the first element is equal to 1.
# We'll divide the row by the value of A[0, 0].
# This will get us in trouble though if A[0, 0] equals 0, so first we'll test for that,
# and if this is true, we'll add one of the lower rows to the first one before the division.
# We'll repeat the test going down each lower row until we can do the division.
# There is no need to edit this function.
def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    return A

# First we'll set the sub-diagonal elements to zero, i.e. A[1,0].
# Next we want the diagonal element to be equal to one.
# We'll divide the row by the value of A[1, 1].
# Again, we need to test if this is zero.
# If so, we'll add a lower row and repeat setting the sub-diagonal elements to zero.
# There is no need to edit this function.
def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

# This is the first function that you should complete.
# Follow the instructions inside the function at each comment.
def fixRowTwo(A) :
    # Insert code below to set the sub-diagonal elements of row two to zero (there are two of them).
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    # Next we'll test that the diagonal element is not zero.
    if A[2,2] == 0 :
        # Insert code below that adds a lower row to row 2.
        A[2] = A[2] + A[3]
        # Now repeat your code which sets the sub-diagonal elements to zero.
        A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Finally set the diagonal element to one by dividing the whole row by that element.
    A[2] = A[2] / A[2,2]
    return A

# You should also complete this function
# Follow the instructions inside the function at each comment.
def fixRowThree(A) :
    # Insert code below to set the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    # Complete the if statement to test if the diagonal element is zero.
    if A[3,3] == 0:
        raise MatrixIsSingular()
    # Transform the row to set the diagonal element to one.
    A[3] = A[3] / A[3,3]
    return A

In [12]:
def gsBasis4(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # The zeroth column is easy, since it has no other vectors to make it normal to.
    # All that needs to be done is to normalise it. I.e. divide by its modulus, or norm.
    B[:, 0] = B[:, 0] / la.norm(B[:, 0])
    # For the first column, we need to subtract any overlap with our new zeroth vector.
    B[:, 1] = B[:, 1] - B[:, 1] @ B[:, 0] * B[:, 0]
    # If there's anything left after that subtraction, then B[:, 1] is linearly independant of B[:, 0]
    # If this is the case, we can normalise it. Otherwise we'll set that vector to zero.
    if la.norm(B[:, 1]) > verySmallNumber :
        B[:, 1] = B[:, 1] / la.norm(B[:, 1])
    else :
        B[:, 1] = np.zeros_like(B[:, 1])
    # Now we need to repeat the process for column 2.
    # Insert two lines of code, the first to subtract the overlap with the zeroth vector,
    # and the second to subtract the overlap with the first.
    B[:,2] = B[:,2] - B[:,2] @ B[:,0] * B[:,0]
    B[:,2] = B[:,2] - B[:,2] @ B[:,1] * B[:,1]
    # Again we'll need to normalise our new vector.
    # Copy and adapt the normalisation fragment from above to column 2.
    if la.norm(B[:,2]) > verySmallNumber:
        B[:,2] = B[:,2] / la.norm(B[:,2])
    else:
        B[:,2] = np.zeros_like(B[:,2])
    # Finally, column three:
    # Insert code to subtract the overlap with the first three vectors.
    B[:,3] = B[:,3] - B[:,3] @ B[:,0] * B[:,0]
    B[:,3] = B[:,3] - B[:,3] @ B[:,1] * B[:,1]
    B[:,3] = B[:,3] - B[:,3] @ B[:,2] * B[:,2]
    # Now normalise if possible
    if la.norm(B[:,3]) > verySmallNumber:
        B[:,3] = B[:,3] / la.norm(B[:,3])
    else:
        B[:,3] = np.zeros_like(B[:,3])
    # Finally, we return the result:
    return B

# The second part of this exercise will generalise the procedure.
# Previously, we could only have four vectors, and there was a lot of repeating in the code.
# We'll use a for-loop here to iterate the process for each vector.
def gsBasis(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]) :
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # Complete the code to subtract the overlap with previous vectors.
            # you'll need the current vector B[:, i] and a previous vector B[:, j]
            B[:, i] = B[:,i] - B[:,i] @ B[:,j] * B[:,j]
        # Next insert code to do the normalisation test for B[:, i]
        if la.norm(B[:,i]) > verySmallNumber:
            B[:,i] = B[:,i] / la.norm(B[:,i])
        else:
            B[:,i] = np.zeros_like(B[:,i])
    # Finally, we return the result:
    return B

# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(A) :
    return np.sum(la.norm(gsBasis(A), axis=0))

In [30]:
def build_reflection_matrix(bearBasis) : # The parameter bearBasis is a 2×2 matrix that is passed to the function.
    # Use the gsBasis function on bearBasis to get the mirror's orthonormal basis.
    E = gsBasis(bearBasis)
    # Write a matrix in component form that perform's the mirror's reflection in the mirror's basis.
    # Recall, the mirror operates by negating the last component of a vector.
    # Replace a,b,c,d with appropriate values
    TE = np.array([[1, 0],
                   [0, -1]])
    # Combine the matrices E and TE to produce your transformation matrix.
    T = E @ TE @ transpose(E)
    # Finally, we return the result. There is no need to change this line.
    return T

In [132]:
T = np.array([[3/2,-1],[-1/2,1/2]])
C = np.array([[-1-math.sqrt(3),-1+math.sqrt(3)],[1,1]])
D = inv(C) @ T @ C
D

array([[ 1.86602540e+00,  5.55111512e-17],
       [-9.71445147e-17,  1.33974596e-01]])

In [78]:
T2 = C @ D @ D @ inv(C)
T2

array([[ 2.75, -2.  ],
       [-1.  ,  0.75]])

In [42]:
C = np.array([[1,0],[1,1]])
D = np.array([[1,0],[0,-1]])
T5 = C @ D @ D @ D @ D @ D @ inv(C)
T5

array([[ 1.,  0.],
       [ 2., -1.]])

In [56]:
def page_rank(linkMatrix, d):    
    import numpy.linalg as la
    n = linkMatrix.shape[0]
    M = d * linkMatrix + (1-d)/n * np.ones([n,n])
    r = 100 * np.ones(n) / n
    lastR = r
    r = M @ r
    i = 0
    while la.norm(lastR - r) > 0.01:
        lastR = r
        r = M @ r
        i += 1
    return r

In [82]:
A = np.array([[3/2, -1],[-1/2,1/2]])
la.eig(A)

(array([1.8660254, 0.1339746]), array([[ 0.9390708 ,  0.59069049],
        [-0.34372377,  0.80689822]]))

In [129]:
C = np.array([[-1-math.sqrt(5)],[1]])
A @ C

array([[-5.85410197],
       [ 2.11803399]])